npcs:
  '1': "Jack"
  '2': "Blacksmith"

items:
  steak: "COOKED_BEEF"
  cod: "COD"
  leatherHelmet: "LEATHER_HELMET"
  leatherChestplate: "LEATHER_CHESTPLATE"
  leatherLeggings: "LEATHER_LEGGINGS"
  leatherBoots: "LEATHER_BOOTS"
