npcs:
  JackNpc: "citizens 1"
  BlacksmithNpc: "citizens 2"
npc_conversations:
  JackNpc: "Jack"
  BlacksmithNpc: "Blacksmith"

items:
  steak: "COOKED_BEEF"
  cod: "COD"
  ironHelmet: "IRON_HELMET"
  ironChestplate: "IRON_CHESTPLATE"
  ironLeggings: "IRON_LEGGINGS"
  ironBoots: "IRON_BOOTS"
