npcs:
  JonesNpc: "citizens 0"
npc_conversations:
  JonesNpc: "Jones"

items:
  oakLog: "simple minecraft:oak_log"
  jonesAxe: "simple IRON_AXE \"name:<gray>Jones Hardened Axe\" enchants:DIG_SPEED:2,DURABILITY:4"
