npcs:
  JonesNpc: "citizens 0"
npc_conversations:
  JonesNpc: "Jones"

items:
  oakLog: "simple minecraft:oak_log"
  jonesAxe: "simple IRON_AXE name:ยง7Jones_Hardened_Axe enchants:DIG_SPEED:2,DURABILITY:4"
