npcs:
  '0': "Jones"

items:
  oakLog: "minecraft:oak_log"
  jewelry: "minecraft:diamond"

conversations:
  Jones:
    quester: "Jones"
    first: "questAlreadyDone,noWoodInInv,wrongWood,questNotDone,questDone,firstGreeting"
    NPC_options:
      firstGreeting:
        text: "Yoo! You look like you can handle those heavy axes to cut down some trees..?"
        pointer: "probably"
      woodAmountAnswer:
        text: "Bring me 20 logs of oak and you will get my special axe for woodcutting!"
        pointer: "letsDoIt"
      seeYou:
        text: "See you soon!"
      noWoodInInv:
        text: "Looks like you don't have the required wood with you. Bring me 20 oak logs!"
        conditions: "startedTag,woodcuttingDoneTag,!logsInInventory"
      wrongWood:
        text: "Oh you still need some time for the mission?.. You have to actually chop them down and not take it from your chest!"
        conditions: "startedTag,!woodcuttingDoneTag,logsInInventory"
      questNotDone:
        text: "Oh you still need some time for the mission?.."
        conditions: "startedTag,!woodcuttingDoneTag,!logsInInventory"
      questDone:
        text: "That's the wood I was looking for! Thank you so much! Here is my special axe for my special friend."
        events: "questDone"
        conditions: "woodcuttingDoneTag,logsInInventory"
      questAlreadyDone:
        text: "Hey! I don't need you anymore. Thanks again for the help."
        conditions: "questDoneTag"
    player_options:
      probably:
        text: "Yes I can do that for you! How much wood do you need?"
        pointer: "woodAmountAnswer"
      letsDoIt:
        text: "Alright let's get the job done!"
        pointer: "seeYou"
        events: "questStarted"

events:
  questStarted: "folder startedTagAdd,addWoodcuttingObj"
  startedTagAdd: "tag add startedTag"
  addWoodcuttingObj: "objective add woodCuttingObj"

  questDone: "folder takeWoodFromPlayer,rewardPlayer,addQuestDoneTag"
  takeWoodFromPlayer: "take oakLog:10"
  rewardPlayer: "give jewelry:2"
  addQuestDoneTag: "tag add questDoneTag"

  addWoodcuttingDoneTag: "tag add woodcuttingDoneTag"

objectives:
  woodCuttingObj: "block OAK_LOG -10 notify events:addWoodcuttingDoneTag"

conditions:
  woodcuttingDoneTag: "tag woodcuttingDoneTag"
  logsInInventory: "item oakLog:10"
  questDoneTag: "tag questDoneTag"
  startedTag: "tag startedTag"